---
- hosts: all
  tasks:
    - name: install live build
      apt: name=live-build update_cache=yes
      sudo: yes

    - name: enable repository
      apt_repository: repo='deb https://dl.bintray.com/anansi/anansi stable main' filename=anansi

    - name: install key
      apt_key: keyserver=hkps.pool.sks-keyservers.net id=7B515ADA

